### ISSUE TITLE
[CKAN] Error at downloading 1.28.10 version 

### ISSUE THREAD

**Issue by zfxstd** [sswelm/KSP-Interstellar-Extended#684]
I have problem with downloading latest (1.28.10) version of KIE via CKAN.
If i trying to download 1.28.9, it works.

But if i trying to download latest, I got this error:

```
CKAN.InvalidModuleFileKraken: KSPInterstellarExtended 1.28.10: C:\Users\noname\AppData\Local\Temp\tmp5534.tmp is not a valid ZIP file: Error in step EntryData for GameData/InterstellarFuelSwitch/Parts/@thumbs/KspiInflatableLiquidTank_icon.png: CRC mismatch
   at CKAN.NetModuleCache.Store(CkanModule module, String path, String description, Boolean move)
   at CKAN.NetAsyncModulesDownloader.ModuleDownloadComplete(Uri url, String filename, Exception error)
```

**Comment by galaxyentity904** [comment]
Im having the same error

**Comment by zfxstd** [comment]
Ok, seems like it fixed now and updating without problems.

**Comment by galaxyentity904** [comment]
The mod is also working for me now too
